spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/JWKS
          issuer-uri: http://localhost:9999
  application:
    name: demo-a2a-authenticated

a2a:
  agent:
    base-url: http://localhost:8080
    well-known-agent-name: hello-world
